Unit Test Case Generation
ibm-granite-community/granite-code-cookbook pull request #131
Opened 2024-10-06 22:40 UTC by sree24lakshmi

Revert find_langchain_model changes

2024-10-07 14:12 UTC, rawkintrevo commented
@fayvor possibly of interest to you too

2024-10-07 14:58 UTC, deanwampler reviewed
This probably can't be fixed, the indentation of the generated code is terrible. Sometimes there is no indentation when I run it, which is obviously bad. Most of the time, one space is used, but only at the first level. Also, the tests themselves are very underwhelming. At best they show you the basics of how to use an API, but the user will have a lot of work to do afterwards.

2024-10-14 07:35 UTC, sree24lakshmi commented
Hi Dean

I agree and have raised the indentation concern with Adam prior to submitting a pull request. As part of the recent code changes that includes invocation of model via langchain replicate directly instead of utils package module, the indentation was retained. The latest code has been uploaded. Our understanding has been to show the generic usage of the model to generate use cases using different test libraries. Please advise if you need us to include any additional use cases/test criteria. Kindly review and share if any further feedback.

2024-10-14 12:55 UTC, fayvor commented
@deanwampler @sree24lakshmi I wouldn't put too much effort into adjusting the prompt to get the right output indentation. As long as the code works, you can run it through a formatter (eg. [black](https://github.com/psf/black)). 

In fact, you could do that in the recipe. You can prompt the LLM to output only code, and use this:
```
import black
formatted_code = black.format_str(code_string, mode=black.FileMode())
```

2024-10-14 14:34 UTC, fayvor commented
@sree24lakshmi is it worth adding a re-try when the generated python code isn't executable? As folks are learning with AI agents, fault-tolerance has to be built-in to production systems. Retries are one approach to this. Maybe something we can demonstrate here?

2024-10-14 14:40 UTC, sree24lakshmi commented
Sure, @fayvor. We could do that but I believe the indentation issue is fixed in the latest code.  Our observation has been that missing indentation scenario was encountered while invoking the model via langchain utils repo package. As per the latest code, with the direct call to langchain replicate model, this no longer seems to be the case as the indented code is returned always.

2024-10-14 19:55 UTC, deanwampler requested changes
I'll give you a PR for this branch with my suggested changes. If you are okay with them, more or less, then I'm ready to approve this PR.

2024-10-14 19:55 UTC, deanwampler commented on recipes/UnitTest_Code_Gen/unit_test_cases_gen_new.ipynb
> +      "Granite response from Replicate: Here is the unit test code using pytest library package for the given code:\n",
I'll give you a PR that adds the instructions in the prompt to mock out Kafka.

2024-10-15 09:22 UTC, sree24lakshmi commented on recipes/UnitTest_Code_Gen/unit_test_cases_gen_new.ipynb
> +    "#!python -m pip install langchain_community replicate"
This is done

2024-10-15 09:22 UTC, sree24lakshmi commented on recipes/UnitTest_Code_Gen/unit_test_cases_gen_new.ipynb
> +    "#!python -m pip install git+https://github.com/ibm-granite-community/utils"
Done

2024-10-15 09:23 UTC, sree24lakshmi commented on recipes/UnitTest_Code_Gen/unit_test_cases_gen_new.ipynb
> +    "from ibm_granite_community.langchain_utils import set_env_var, get_env_var"
This is done as well

2024-10-15 09:23 UTC, sree24lakshmi commented on recipes/UnitTest_Code_Gen/unit_test_cases_gen_new.ipynb
> +    "Here: Created a  environment variable `REPLICATE_API_TOKEN='xxxxx'` in `.env` file in the current directory."
Implemented the same

2024-10-15 09:23 UTC, sree24lakshmi commented on recipes/UnitTest_Code_Gen/unit_test_cases_gen_new.ipynb
> +      "Granite response from Replicate: Here is the unit test code using pytest library package for the given code:\n",
This too has been revised

2024-10-15 13:52 UTC, fayvor commented on recipes/UnitTest_Code_Gen/unit_test_cases_gen.ipynb
> +    "!pip install git+https://github.com/ibm-granite-community/utils"
This and the `pip install langchain_community replicate` above can be pulled in with:
`!pip install git+https://github.com/ibm-granite-community/granite-kitchen`

As shown [here](https://github.com/ibm-granite-community/granite-kitchen/blob/main/recipes/Getting_Started/Getting_Started_with_Replicate.ipynb). You may just want to check that you are getting the same version of replicate.

2024-10-15 13:55 UTC, fayvor commented
> multiple retry attempts, rarely yielded successful outcome (indented code).

Makes sense. I'm glad you were able to fix the indentation issue. It's odd to me that the same remote model would return different results, but I guess it's possible that you were using a version of the replicate library that permuted the input or the output.

@sree24lakshmi if you are a member of the IBM Granite org on Replicate, you can look at the outputs server-side by clicking through on your request id [here](https://replicate.com/predictions).

2024-10-15 16:03 UTC, deanwampler commented
Thanks for the updates @sree24lakshmi! I'll review shortly.

2024-10-15 17:44 UTC, deanwampler approved these changes
Done

2024-10-15 18:11 UTC, merged

2024-10-15 18:11 UTC, deanwampler commented
Done!!

2024-10-23 09:06 UTC, sree24lakshmi commented
> > multiple retry attempts, rarely yielded successful outcome (indented code).
> 
> Makes sense. I'm glad you were able to fix the indentation issue. It's odd to me that the same remote model would return different results, but I guess it's possible that you were using a version of the replicate library that permuted the input or the output.
> 
> @sree24lakshmi if you are a member of the IBM Granite org on Replicate, you can look at the outputs server-side by clicking through on your request id [here](https://replicate.com/predictions). That might help ensure no inputs or outputs are getting changed by the client.

Thank you @fayvor

2024-10-23 09:06 UTC, sree24lakshmi commented
> Done!!

Thank you @deanwampler for all the support!!